version: '3.8'

services:

  postgres:
    image: postgres:16-alpine
    container_name: shopstream-postgres
    environment:
      POSTGRES_USER: shopstream
      POSTGRES_PASSWORD: shopstream123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shopstream-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopstream"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shopstream-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - shopstream-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: shopstream-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - shopstream-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: shopstream-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # TWO listeners:
      # PLAINTEXT_HOST → localhost:9092  (your Spring app on Windows)
      # PLAINTEXT      → kafka:29092     (kafka-ui inside Docker)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - shopstream-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: shopstream-kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      # Uses internal Docker hostname — not localhost
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - shopstream-network

volumes:
  postgres_data:

networks:
  shopstream-network:
    driver: bridge